# Generated by Django 5.0.1 on 2024-09-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.TextField(blank=True),
        ),
    ]
