# Generated by Django 5.0.1 on 2024-04-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='entregableAdministrativo',
        ),
        migrations.AddField(
            model_name='investigador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investigador',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='EntregableAdministrativoProducto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('calidad', models.CharField(max_length=50)),
                ('entregable', models.CharField(max_length=50)),
                ('pendiente', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto')),
            ],
            options={
                'db_table': 'proyecto_EntregableAdministrativoProducto',
            },
        ),
        migrations.CreateModel(
            name='EntregableAdministrativoProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('calidad', models.CharField(max_length=50)),
                ('entregable', models.CharField(max_length=50)),
                ('pendiente', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50)),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
            options={
                'db_table': 'proyecto_EntregableAdministrativoProyecto',
            },
        ),
        migrations.DeleteModel(
            name='EntregableAdministrativo',
        ),
    ]
