# Generated by Django 5.0.1 on 2024-09-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
