# Generated by Django 5.0.1 on 2024-04-17 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_proyecto_entregableadministrativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='observacion',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='observacion',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.CreateModel(
            name='ConfiguracionEntregableProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto')),
            ],
            options={
                'db_table': 'proyecto_ConfiguracionEntregableProducto',
            },
        ),
        migrations.CreateModel(
            name='AvanceEntregableProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('soporte', models.FileField(blank=True, max_length=1000, upload_to='uploadsProducto/')),
                ('fecha', models.DateField()),
                ('estadoProceso', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Corregir', 'Corregir'), ('Espera', 'Espera')], default='Espera', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('configuracionEntregableProducto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.configuracionentregableproducto')),
            ],
            options={
                'db_table': 'proyecto_AvanceEntregableProducto',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEntregableProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
            options={
                'db_table': 'proyecto_ConfiguracionEntregableProyecto',
            },
        ),
        migrations.CreateModel(
            name='AvanceEntregableProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('soporte', models.FileField(blank=True, max_length=1000, upload_to='uploadsProducto/')),
                ('fecha', models.DateField()),
                ('estadoProceso', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Corregir', 'Corregir'), ('Espera', 'Espera')], default='Espera', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('configuracionEntregableProyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.configuracionentregableproyecto')),
            ],
            options={
                'db_table': 'proyecto_AvanceEntregableProyecto',
            },
        ),
    ]
