# Generated by Django 5.0.1 on 2024-04-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_producto_observacion_proyecto_observacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avanceentregableproducto',
            name='estadoProceso',
        ),
        migrations.RemoveField(
            model_name='avanceentregableproyecto',
            name='estadoProceso',
        ),
        migrations.AddField(
            model_name='avanceentregableproducto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avanceentregableproyecto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionentregableproducto',
            name='estadoProceso',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Corregir', 'Corregir'), ('Espera', 'Espera')], default='Espera', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionentregableproducto',
            name='observacion',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='configuracionentregableproyecto',
            name='estadoProceso',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Corregir', 'Corregir'), ('Espera', 'Espera')], default='Espera', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionentregableproyecto',
            name='observacion',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='avanceentregableproducto',
            name='soporte',
            field=models.FileField(blank=True, max_length=1000, upload_to='uploadsAvancesProducto/'),
        ),
        migrations.AlterField(
            model_name='avanceentregableproyecto',
            name='soporte',
            field=models.FileField(blank=True, max_length=1000, upload_to='uploadsAvanceProyecto/'),
        ),
        migrations.AlterField(
            model_name='configuracionentregableproducto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
