# Generated by Django 5.0.1 on 2024-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avanceentregableproyecto',
            name='soporte',
            field=models.TextField(blank=True),
        ),
    ]
