# Generated by Django 5.0.1 on 2024-04-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_remove_entregableadministrativoproyecto_proyecto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=150)),
                ('remitente', models.CharField(max_length=150)),
                ('destinatario', models.CharField(max_length=150)),
                ('mensaje', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'proyecto_Notificaciones',
            },
        ),
    ]
