# Generated by Django 5.0.1 on 2024-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_producto_soporte_alter_proyecto_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Soporte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
