# Generated by Django 5.0.1 on 2024-05-01 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigador',
            name='tipPosgrado',
        ),
        migrations.RemoveField(
            model_name='investigador',
            name='tipPregrado',
        ),
        migrations.AddField(
            model_name='posgrado',
            name='Investigador_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.investigador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posgrado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posgrado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pregrado',
            name='Investigador_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='proyecto.investigador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregrado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pregrado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='posgrado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pregrado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
