# Generated by Django 5.0.1 on 2024-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_producto_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avanceentregableproducto',
            name='soporte',
            field=models.TextField(blank=True, max_length=7000000),
        ),
        migrations.AlterField(
            model_name='avanceentregableproyecto',
            name='soporte',
            field=models.TextField(blank=True, max_length=7000000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Soporte',
            field=models.TextField(blank=True, max_length=7000000, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Soporte',
            field=models.TextField(blank=True, max_length=7000000),
        ),
    ]
