# Generated by Django 5.0.1 on 2024-10-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_tipoproducto_proyecto_cantidadproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='acta',
            field=models.TextField(blank=True, max_length=7000000),
        ),
    ]
